bases/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from bases.views import Home
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('login/', auth_views.LoginView.as_view(template_name = 'bases/login.html' ), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='bases/login.html'),name='logout'),
]

farmacia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls','bases'), namespace='bases')),
    path('mva/', include(('mva.urls','mva'), namespace='mva')),
    path('admin/', admin.site.urls),
]

mva/urls.py
from django.urls import path

from .views import CategoriaView, CategoriaNew, CategoriaEdit, \
    CategoriaDel, SubCategoriaView

urlpatterns = [
    path('categorias/',CategoriaView.as_view(), name='list_categoria'),
    path('categorias/new',CategoriaNew.as_view(), name='new_categoria'),
    path('categorias/edit/<int:pk>',CategoriaEdit.as_view(), name='edit_categoria'),
    path('categorias/delete/<int:pk>',CategoriaDel.as_view(), name='del_categoria'),

    path('subcategorias/',SubCategoriaView.as_view(), name='list_subcategoria'),
]

bases/models.py
from django.db import models

from django.contrib.auth.models import User

#fc = fecha de creacion, fm = fecha modifichado, uc = usuario, um = usuario modifica


class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now_add=True)
    uc = models.ForeignKey(User, on_delete= models.CASCADE)
    um = models.IntegerField(blank=True, null=True)

    class Meta:
        abstract=True

mva/models.py
from django.db import models

from bases.models import ClaseModelo

class Categoria(ClaseModelo):
    descripcion = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return '{}'.format(self.descripcio)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save()

    class Meta:
        verbose_name_plural = "Categorias"

class SubCategoria(ClaseModelo):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=100)


    def __str__(self):
        return '{}:{}'.format(self.categoria.descripcio, self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(SubCategoria, self).save()

    class Meta:
        verbose_name_plural = "SubCategorias"
        unique_together = ('categoria','descripcion')

mva/forms.py
from django import forms

from .models import Categoria

class CategoriaForm(forms.ModelForm):
    class Meta:
        model=Categoria
        fields = ['descripcion','estado']
        labels = {'descripcion':"Descripcion de la Categoria",
                'estado':"estado"}
        widget={'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

bases/views.py
from django.shortcuts import render

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

class Home(LoginRequiredMixin, generic.TemplateView):
    template_name = 'bases/home.html'
    login_url = 'bases:login'

mva/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Categoria, SubCategoria
from .forms import CategoriaForm

class CategoriaView(LoginRequiredMixin, generic.ListView):
    model = Categoria
    template_name = "mva/list_categoria.html"
    context_object_name = "obj"
    login_url = 'bases:login'

class CategoriaNew(LoginRequiredMixin, generic.CreateView):
    model=Categoria
    template_name="mva/form_categoria.html"
    context_object_name = "obj"
    form_class=CategoriaForm
    success_url=reverse_lazy("mva:list_categoria")
    logi_url="base:login"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class CategoriaEdit(LoginRequiredMixin, generic.UpdateView):
    model=Categoria
    template_name="mva/form_categoria.html"
    context_object_name = "obj"
    form_class=CategoriaForm
    success_url=reverse_lazy("mva:list_categoria")
    logi_url="base:login"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class CategoriaDel(LoginRequiredMixin, generic.DeleteView):
    model=Categoria
    template_name="mva/del_categoria.html"
    context_object_name = "obj"
    form_class=CategoriaForm
    success_url=reverse_lazy("mva:list_categoria")
    logi_url="base:login"

class SubCategoriaView(LoginRequiredMixin, generic.ListView):
    model = SubCategoria
    template_name = "mva/list_subcategoria.html"
    context_object_name = "obj"
    login_url = 'bases:login'

bases/templates/bases/home.html
{% extends 'base/base.html' %}

bases/templates/bases/login.html
{% extends 'base/base.html' %}
{% block navbar %}{% endblock%}
{% block sidebar %}{% endblock%}
{% block content %}{% endblock%}
{% block footer %}{% endblock%}
{% block js_page %}{% endblock %}
{% block login %}
<div class="hold-transition login-page">
  <div class="login-logo">
    <a href=""><b>Admin</b></a>
  </div>
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Inicia sesión para comenzar tu sesión</p>

      <form class="user" method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
          <input type="text" class="form-control" id="id_username" name="username" placeholder="Usuario">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user-friends"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" id="id_password" name="password" placeholder="Password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-user btn-block">Ingresar</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock login %}

mva/templates/mva/del_categoria.html
{% extends 'base/base.html' %}
{% block content  %}
<form method="POST" class="form-inline">
  {% csrf_token %}
<div class="content-wrapper ">
  <div class="container-fluid">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">Eliminar? {{ obj.descripcion }}</h3>
        <div class="card-tools">
        </div>
        <!-- /.card-tools -->
      </div>
      <!-- /.card-header -->
      <div class="card-body">
        <button type="submit" class="btn btn-danger">Si, Eliminar</button>
        <a href="{% url 'mva:list_categoria' %}" class="btn btn-success"><span
          class="fa fa-undo"></span>Cancelar</a>
      </div>
    </div>
    </div>
  </div>
{% endblock %}
{% block footer %}{% endblock %}

mva/templates/mva/form_categoria.html
{% extends 'base/base.html' %}
f
{% block content %}
<form method="POST" class="form-inline">
  {% csrf_token %}
  <div class="content-wrapper col-xl-6 col-md-6 mb-6">
           <div class="card card-success">
             <div class="card-header">
               <h3 class="card-title">Nueva Categoria</h3>

               <div class="card-tools">
                 <button type="button" class="btn btn-tool" data-card-widget="card-refresh" data-source="/pages/widgets.html" data-source-selector="#card-refresh-content"><i class="fas fa-sync-alt"></i></button>
                 <button type="button" class="btn btn-tool" data-card-widget="maximize"><i class="fas fa-expand"></i></button>
                 <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                 <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
               </div>
               <!-- /.card-tools -->
             </div>
             <!-- /.card-header -->
             <div class="card-body">
               <div class="dropdwon-divider"></div>
               <div class="row">
                 <div class="col-10">
                   <div class="input-group">
                     <input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" placeholder="Descripcion"
                     value="{% if obj %} {{ obj.descripcion }} {% endif %}">
                   </div>
                   <div class="col-2">
                     <div class="form-group">
                       <label for="id_estado">Estado</label>
                       <input type="checkbox" name="estado" class="form-control" id="id_estado"
                         {% if obj.estado %} checked {% endif %}>
                     </div>
                   </div>
                   <div class="dropdwon-divider"></div>
                   <div class="row">
                     <div class="col">
                       <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardad</button>
                       <a href="{% url 'mva:list_categoria' %}" class="btn btn-success"><span class=" fa fa-undo"</span>Cancelar</a>

                     </div>

                   </div>
                 </div>
               </div>
             </div>
             <!-- /.card-body -->
           </div>
           <!-- /.card -->
         </div>
{% endblock%}
{% block footer %}{% endblock%}
{% block js_page %}{% endblock %}

mva/templates/mva/list_categoria.html
{% extends 'base/base.html' %}
{% block footer %}{% endblock %}
{% block content %}
<!-- Content Wrapper. Contains page content -->
 <div class="content-wrapper">
   <!-- Content Header (Page header) -->
   <section class="content-header">
     <div class="container-fluid">
       <div class="row mb-2">
         <div class="col-sm-6">
           <h1>Categorias </h1>
         </div>
         <div class="col-sm-6">
           <ol class="breadcrumb float-sm-right">
             <li class="breadcrumb-item"><a href="{% url 'mva:list_categoria' %}">Regresar</a></li>
             <li class="breadcrumb-item"><a href="{% url 'mva:new_categoria' %}">Agregar</a></li>
             <li class="breadcrumb-item active">Categorias</li>
           </ol>
         </div>
       </div>
     </div><!-- /.container-fluid -->
   </section>

   <!-- Main content -->
   <section class="content">

     <!-- Default box -->
     <div class="card">
       <div class="card-header">
         <h3 class="card-title">Menu</h3>

         <div class="card-tools">
           <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
             <i class="fas fa-minus"></i></button>
           <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
             <i class="fas fa-times"></i></button>
         </div>
       </div>
       <div class="card-body p-0">
         <table class="table table-striped projects">
             <thead>
                 <tr>
                     <th style="width: 20%">
                         Categoria
                     </th>
                     <th style="width: 20%">
                         F. Creacion
                     </th>
                     <th style="width: 20%">
                         F. Modificacion
                     </th>
                     <th style="width: 8%" class="text-center">
                         Estado
                     </th>
                     <th class="all" style="width: 20%">
                     </th>
                 </tr>
             </thead>
             <tbody>
               {% for item in obj %}
                 <tr>
                     <td>
                       {{ item.descripcion }}
                     </td>
                     <td>
                       {{ item.fc|date:"d/m/Y H:i:s" }}
                     </td>
                     <td>
                       {{ item.fm}}
                     </td>
                     <td>
                      {{ item.estado|yesno:"Activo,Inactivo" }}
                     </td>
                     <td class="project-actions text-right">
                           <a class="btn btn-info btn-sm" href="{% url 'mva:edit_categoria' item.id %}">
                               <i class="fas fa-pencil-alt">
                               </i>
                               Edit
                           </a>
                           <a class="btn btn-danger btn-sm" href="{% url 'mva:del_categoria' item.id %}">
                               <i class="fas fa-trash">
                               </i>
                               Delete
                           </a>
                       </td>
                 </tr>
               </tbody>
               {% endfor %}
              </div>
            </div>
          </div>
{% endblock%}
{% block js_page %}
<script>
  $(function () {
    $('.table').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });
</script>
{% endblock %}

mva/templates/mva/list_subcategoria.html
{% extends 'base/base.html' %}
{% block footer %}{% endblock %}
{% block content %}
<!-- Content Wrapper. Contains page content -->
 <div class="content-wrapper">
   <!-- Content Header (Page header) -->
   <section class="content-header">
     <div class="container-fluid">
       <div class="row mb-2">
         <div class="col-sm-6">
           <h1>Sub Categorias </h1>
         </div>
         <div class="col-sm-6">
           <ol class="breadcrumb float-sm-right">
             <li class="breadcrumb-item"><a href="{% url 'mva:list_categoria' %}">Regresar</a></li>
             <li class="breadcrumb-item"><a href="{% url 'mva:new_categoria' %}">Agregar</a></li>
             <li class="breadcrumb-item active">Sub Categorias</li>
           </ol>
         </div>
       </div>
     </div><!-- /.container-fluid -->
   </section>

   <!-- Main content -->
   <section class="content">

     <!-- Default box -->
     <div class="card">
       <div class="card-header">
         <h3 class="card-title">Menu</h3>

         <div class="card-tools">
           <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
             <i class="fas fa-minus"></i></button>
           <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
             <i class="fas fa-times"></i></button>
         </div>
       </div>
       <div class="card-body p-0">
         <table class="table table-striped projects">
             <thead>
                 <tr>
                     <th style="width: 20%">
                         Categoria
                     </th>
                     <th style="width: 20%">
                         Sub Categoria
                     </th>
                     <th style="width: 20%">
                         F. Creacion
                     </th>
                     <th style="width: 20%">
                         F. Modificacion
                     </th>
                     <th style="width: 8%" class="text-center">
                         Estado
                     </th>
                     <th class="all" style="width: 20%">
                     </th>
                 </tr>
             </thead>
             <tbody>
               {% for item in obj %}
                 <tr>
                   <td>
                     {{ item.categoria }}
                   </td>
                     <td>
                       {{ item.descripcion }}
                     </td>
                     <td>
                       {{ item.fc|date:"d/m/Y H:i:s" }}
                     </td>
                     <td>
                       {{ item.fm}}
                     </td>
                     <td>
                      {{ item.estado|yesno:"Activo,Inactivo" }}
                     </td>
                     <td class="project-actions text-right">
                           <a class="btn btn-info btn-sm" href="{% url 'mva:edit_categoria' item.id %}">
                               <i class="fas fa-pencil-alt">
                               </i>
                               Edit
                           </a>
                           <a class="btn btn-danger btn-sm" href="{% url 'mva:del_categoria' item.id %}">
                               <i class="fas fa-trash">
                               </i>
                               Delete
                           </a>
                       </td>
                 </tr>
               </tbody>
               {% endfor %}
              </div>
            </div>
          </div>
{% endblock%}
{% block js_page %}
<script>
  $(function () {
    $('.table').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });
</script>
{% endblock %}